// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEZyvWmKK7uGB4YrEvCuthOWTBx0AhrB0',
    appId: '1:250210685012:web:03d2103c046608fd63ddc1',
    messagingSenderId: '250210685012',
    projectId: 'realtime-chat-app-5d6cf',
    authDomain: 'realtime-chat-app-5d6cf.firebaseapp.com',
    storageBucket: 'realtime-chat-app-5d6cf.appspot.com',
    measurementId: 'G-8ZQPXN124J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR-u1HKbuZDL7zge2Pzj9RGqbrbBxIhJg',
    appId: '1:250210685012:android:ee20c0d7b2b4509963ddc1',
    messagingSenderId: '250210685012',
    projectId: 'realtime-chat-app-5d6cf',
    storageBucket: 'realtime-chat-app-5d6cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ93-LatjUBYKt1Wy5ZET3y2t2bYmI_E4',
    appId: '1:250210685012:ios:299c089acb8bb07363ddc1',
    messagingSenderId: '250210685012',
    projectId: 'realtime-chat-app-5d6cf',
    storageBucket: 'realtime-chat-app-5d6cf.appspot.com',
    iosBundleId: 'com.example.mobieTicketApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ93-LatjUBYKt1Wy5ZET3y2t2bYmI_E4',
    appId: '1:250210685012:ios:299c089acb8bb07363ddc1',
    messagingSenderId: '250210685012',
    projectId: 'realtime-chat-app-5d6cf',
    storageBucket: 'realtime-chat-app-5d6cf.appspot.com',
    iosBundleId: 'com.example.mobieTicketApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEZyvWmKK7uGB4YrEvCuthOWTBx0AhrB0',
    appId: '1:250210685012:web:c11854bdcd58179563ddc1',
    messagingSenderId: '250210685012',
    projectId: 'realtime-chat-app-5d6cf',
    authDomain: 'realtime-chat-app-5d6cf.firebaseapp.com',
    storageBucket: 'realtime-chat-app-5d6cf.appspot.com',
    measurementId: 'G-NJ587CPK2B',
  );

}